### ISSUE TITLE
Exporting and Importing material from csv

### ISSUE THREAD

**Issue by Alisher1994** [kbruxvoort/SSG.extension#6]
Hello! 

When using this command, it returns the error that I indicated in the picture.

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\User\AppData\Roaming\pyRevit\Extensions\pySSG.extension\pySSG.tab\Materials.Panel\Create.pulldown\Materials to CSV.pushbutton\script.py", line 225, in <module>
TypeError: expected index value, got str


Script Executor Traceback:
IronPython.Runtime.Exceptions.TypeErrorException: expected index value, got str
в Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
в Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
в Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
в Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
в IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
в PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

![1](https://github.com/kbruxvoort/SSG.extension/assets/71883135/485b7d11-49c3-4846-82fb-0834e18975d3)

**Comment by J-DBox** [comment]
Same here, though a little different

`IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\User\AppData\Roaming\pyRevit\Extensions\pySSG.extension\pySSG.tab\Materials.Panel\Create.pulldown\Materials to CSV.pushbutton\script.py", line 225, in <module>
TypeError: expected int, got str

Script Executor Traceback:
Microsoft.Scripting.ArgumentTypeException: expected int, got str
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)`

**Comment by ivanzep** [comment]
any solution for this issue?
